# Generated by Django 4.1.3 on 2024-07-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_topic_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='view',
            new_name='views',
        ),
    ]
